# ANALISIS DE INTEGRACIÓN

El análisis de integración es parte de la metodología básica de la econometría moderna. La metodología establece que  los datos que se observan de cualquier fenómeno económico, social o ambiental provienen de una variable aleatoria que se define por un Proceso Generador de Información (PGI) con un modelo estadístico, probabilístico y muestral. La metodología econométrica moderna establece que cualquier indicador o variable se use en el análisis, siempre y cuando cumpla con las tres condiciones para ser aleatoria: 1) Media finita y constante con respecto al tiempo; 2) Varianza finita y constante respecto al tiempo; y, 3) Covarianza finita, constante con respecto al tiempo, pero que dependa del tiempo en la definición de proceso autorregresivo.  A estas tres características  también se les conoce como las condiciones de estacionariedad, debido a que para su cumplimientos el equilibrio debe existir y su dinámica debe ser convergente.   En el caso de que no se cumpla, se establece que la principal causa es debido a una  media no constante y por el equilibrio no es convergente  bajo dos situaciones: 1) no existe;  o,  2) existe pero no es estable. Al primer caso se le conoce como el problema de existencia del equilibrio por una  raíz característica unitaria y al segundo  como el problema de divergencia por una mayor que uno.  Por tanto, el análisis de integración consiste en analizar si los indicadores o variables de interés cumplen o no con ser aleatoria, con la ayuda de los conceptos de estacionario y las pruebas de raíz unitaria. En el caso de que no se cumpla con ser estacionaria, la metodología establece utilizar transformaciones por medio de la eliminación de tendencias deterministas o estocásticas.  

La metodología del  análisis de integración se entiende como el procedimiento para entender  si un indicador o variable cumple con ser aleatoria o estacionaria. La principal causa de porque un indicador o variable no es estacionaria es que sigue una tendencia lineal, cuadrática o exponencial del tipo determinística o estocástica. El procedimiento establece que en el caso de que no se cumpla con la condición de ser estacionaria, entonces  se elimine la tendencia por medio del método de la regresión o las diferencias. Este último método es el más utilizado debido que la variable  transformada se parece más a un proceso aleatorio en varianza y covarianza.

In [1]:
library(urca)

In [2]:
load("BDatos_Integracion.RData")

In [3]:
summary(BDatos)

    Periodo      PIB_Mex        
 1993/01: 1   Min.   : 7817381  
 1993/02: 1   1st Qu.: 9506342  
 1993/03: 1   Median :10637808  
 1993/04: 1   Mean   :10777851  
 1994/01: 1   3rd Qu.:12200173  
 1994/02: 1   Max.   :13937805  
 (Other):81                     

In [4]:
# Se asigna  el logaritmo de la variable de serie de tiempo
# al objeto PIB_MEX y se aplica la primera y segunda 
# diferencia.

# derivada primera y segunda

lpib_mex <- log(BDatos$PIB_Mex)
lpib_mex

[1] 15.90066 15.90177 15.90261 15.94013 15.93199 15.95618 15.95007 15.99131
 [9] 15.92094 15.87186 15.87820 15.92116 15.93721 15.93674 15.94480 16.00136
[17] 15.97978 16.01835 16.02114 16.06952 16.05856 16.06177 16.06541 16.08860
[25] 16.08090 16.08260 16.09279 16.12303 16.13381 16.14197 16.14893 16.16142
[33] 16.13457 16.13637 16.13847 16.15252 16.11185 16.15058 16.14166 16.16253
[41] 16.14320 16.15459 16.14569 16.17993 16.18429 16.19502 16.18611 16.22607
[49] 16.19897 16.22961 16.21956 16.26237 16.25512 16.27721 16.27217 16.30172
[57] 16.28390 16.30434 16.30328 16.33847 16.30522 16.33468 16.31902 16.32723
[65] 16.25150 16.25196 16.27220 16.31673 16.28782 16.31719 16.32517 16.36160
[73] 16.33139 16.34901 16.36605 16.40387 16.37862 16.39282 16.39766 16.43882
[81] 16.38880 16.41071 16.41358 16.45012 16.40790 16.42678 16.43488

In [5]:
d_lpib_mex <- diff(lpib_mex)
d_lpib_mex

[1]  0.0011120885  0.0008378136  0.0375231792 -0.0081381553  0.0241902082
 [6] -0.0061134671  0.0412422777 -0.0703699803 -0.0490803529  0.0063419651
[11]  0.0429611391  0.0160491921 -0.0004755867  0.0080649853  0.0565626296
[16] -0.0215795626  0.0385634689  0.0027917185  0.0483833907 -0.0109653771
[21]  0.0032099311  0.0036437697  0.0231853149 -0.0076963448  0.0017034845
[26]  0.0101855101  0.0302387378  0.0107858919  0.0081605877  0.0069504922
[31]  0.0124913663 -0.0268421096  0.0018002332  0.0020981756  0.0140467869
[36] -0.0406661637  0.0387275912 -0.0089251442  0.0208701643 -0.0193276605
[41]  0.0113878434 -0.0088986213  0.0342371622  0.0043644469  0.0107342558
[46] -0.0089122686  0.0399602595 -0.0270978931  0.0306348628 -0.0100504994
[51]  0.0428121389 -0.0072550977  0.0220951670 -0.0050407667  0.0295536663
[56] -0.0178262927  0.0204392021 -0.0010559323  0.0351946625 -0.0332559186
[61]  0.0294597180 -0.0156582559  0.0082091472 -0.0757306558  0.0004621270
[66]  0.0202424448  0.0445241931 -0.0289110718  0.0293768697  0.0079801539
[71]  0.0364242592 -0.0302038279  0.0176162402  0.0170413400  0.0378148644
[76] -0.0252421088  0.0141965610  0.0048353845  0.0411650104 -0.0500167744
[81]  0.0219030994  0.0028742321  0.0365334675 -0.0422125115  0.0188738518
[86]  0.0081073605

In [6]:
d_lpib_mex2 <- diff(lpib_mex,2)
d_lpib_mex2

[1]  0.0019499021  0.0383609929  0.0293850239  0.0160520529  0.0180767412
 [6]  0.0351288106 -0.0291277026 -0.1194503332 -0.0427383878  0.0493031042
[11]  0.0590103312  0.0155736054  0.0075893987  0.0646276149  0.0349830670
[16]  0.0169839063  0.0413551874  0.0511751093  0.0374180136 -0.0077554460
[21]  0.0068537009  0.0268290847  0.0154889702 -0.0059928603  0.0118889946
[26]  0.0404242479  0.0410246297  0.0189464796  0.0151110799  0.0194418585
[31] -0.0143507433 -0.0250418764  0.0038984088  0.0161449625 -0.0266193768
[36] -0.0019385725  0.0298024470  0.0119450201  0.0015425039 -0.0079398170
[41]  0.0024892221  0.0253385408  0.0386016090  0.0150987026  0.0018219872
[46]  0.0310479910  0.0128623665  0.0035369697  0.0205843634  0.0327616395
[51]  0.0355570412  0.0148400693  0.0170544002  0.0245128995  0.0117273736
[56]  0.0026129094  0.0193832698  0.0341387301  0.0019387439 -0.0037962006
[61]  0.0138014621 -0.0074491087 -0.0675215086 -0.0752685287  0.0207045718
[66]  0.0647666379  0.0156131213  0.0004657979  0.0373570235  0.0444044131
[71]  0.0062204313 -0.0125875878  0.0346575801  0.0548562043  0.0125727555
[76] -0.0110455479  0.0190319455  0.0460003949 -0.0088517641 -0.0281136750
[81]  0.0247773314  0.0394076996 -0.0056790440 -0.0233386597  0.0269812123

In [7]:
# Se asigna la variable de órden en el tiempo
periodo <- BDatos$Periodo
periodo

[1] 1993/01 1993/02 1993/03 1993/04 1994/01 1994/02 1994/03 1994/04 1995/01
[10] 1995/02 1995/03 1995/04 1996/01 1996/02 1996/03 1996/04 1997/01 1997/02
[19] 1997/03 1997/04 1998/01 1998/02 1998/03 1998/04 1999/01 1999/02 1999/03
[28] 1999/04 2000/01 2000/02 2000/03 2000/04 2001/01 2001/02 2001/03 2001/04
[37] 2002/01 2002/02 2002/03 2002/04 2003/01 2003/02 2003/03 2003/04 2004/01
[46] 2004/02 2004/03 2004/04 2005/01 2005/02 2005/03 2005/04 2006/01 2006/02
[55] 2006/03 2006/04 2007/01 2007/02 2007/03 2007/04 2008/01 2008/02 2008/03
[64] 2008/04 2009/01 2009/02 2009/03 2009/04 2010/01 2010/02 2010/03 2010/04
[73] 2011/01 2011/02 2011/03 2011/04 2012/01 2012/02 2012/03 2012/04 2013/01
[82] 2013/02 2013/03 2013/04 2014/01 2014/02 2014/03
87 Levels: 1993/01 1993/02 1993/03 1993/04 1994/01 1994/02 1994/03 ... 2014/03

In [8]:
# Para analzar el comportamiento del PIB de México se 
# grafica la variable PIB_Mex en el tiempo

plot(periodo, lpib_mex, main='Producto Interno Bruto de México')
lines(lpib_mex)

En la gráfica se observa el comportamiento del PIB trimestral de México, donde destaca la presencia de una marcada tendencia positiva, con algunos caídas importantes en los momentos de crisis económicas en  1995, 2001 y 2009.

In [9]:
# Contruyo gráficos con la primera y
# segunda derivada del PIB.

plot(d_lpib_mex, main='Diferencias del logaritmo del PIB de México')
lines(d_lpib_mex, col="black")
lines(d_lpib_mex2, col="red")

De la gráfica 2 se puede observar que con la primera diferencia se estabiliza la media del logaritmo del PIB, con lo cual se infiere que es estacionaria en media. Para revisar si se puede mejor la estabilidad de la media y la varianza, se aplica la segunda diferencia y la gráfica muestra que no se mejora la estabilidad y por tanto es suficiente aplicar la primera diferencia. 

In [10]:
# Aplico la prueba de ADF para establecer si el logaritmo 
# del PIB tiene raíz unitaria y de que tipo:

lc.df <- ur.df(y=BDatos$PIB_Mex, type='trend', lags=4, selectlags=c("AIC"))
summary(lc.df)


############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression trend 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + tt + z.diff.lag)

Residuals:
    Min      1Q  Median      3Q     Max 
-574615  -95764   34540  123051  277485 

Coefficients:
              Estimate Std. Error t value Pr(>|t|)    
(Intercept)  2.906e+06  6.521e+05   4.456 2.87e-05 ***
z.lag.1     -3.715e-01  8.460e-02  -4.392 3.63e-05 ***
tt           2.517e+04  5.737e+03   4.388 3.69e-05 ***
z.diff.lag1  1.466e-01  1.075e-01   1.364    0.177    
z.diff.lag2  1.437e-01  9.528e-02   1.508    0.136    
z.diff.lag3 -9.905e-02  9.544e-02  -1.038    0.303    
z.diff.lag4  6.442e-01  9.336e-02   6.900 1.43e-09 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 186300 on 75 degrees of freedom
Multiple R-squared:  0.6376,	Adjusted R-squared:  0.6086 
F-statistic: 21.99 on 6 and 75 DF, 

Con el criterio de Akaike  se encontró que el valor mínimo se obtiene con una estructura de cuatro rezagos. Los resultados de la prueba ADF  permiten rechazar la hipótesis de raíz unitaria debido a que la tau estimada es mayor en valor absoluto al valor critico del 5% de la prueba: -3.73>-3.45. Lo anterior concuerda con el hecho de tener una serie con tendencia determinista y tal vez sea más adecuado aplicar el método de la regresión que con diferencias para eliminar la tendencia. 
 
Para complementar el análisis anterior, se aplicaron las pruebas ADF con constante y sin constante y tendencia.

In [11]:
lc.df <- ur.df(y=BDatos$PIB_Mex, type='drift', lags=4, selectlags=c("AIC"))
summary(lc.df)


############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression drift 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + z.diff.lag)

Residuals:
    Min      1Q  Median      3Q     Max 
-646264  -79083   40350  121630  342269 

Coefficients:
              Estimate Std. Error t value Pr(>|t|)    
(Intercept)  1.108e+05  1.553e+05   0.714   0.4777    
z.lag.1     -4.646e-03  1.431e-02  -0.325   0.7463    
z.diff.lag1 -1.185e-01  9.901e-02  -1.197   0.2349    
z.diff.lag2 -4.648e-02  9.449e-02  -0.492   0.6242    
z.diff.lag3 -2.746e-01  9.649e-02  -2.846   0.0057 ** 
z.diff.lag4  5.494e-01  1.011e-01   5.432 6.46e-07 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 207500 on 76 degrees of freedom
Multiple R-squared:  0.5445,	Adjusted R-squared:  0.5145 
F-statistic: 18.17 on 5 and 76 DF,  p-value: 8.079e-12


Value of test-statistic is: -0.3247 2.

In [12]:
lc.df <- ur.df(y=BDatos$PIB_Mex, type='none', lags=4, selectlags=c("AIC"))
summary(lc.df)


############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression none 


Call:
lm(formula = z.diff ~ z.lag.1 - 1 + z.diff.lag)

Residuals:
    Min      1Q  Median      3Q     Max 
-638215  -69385   34401  124688  352833 

Coefficients:
             Estimate Std. Error t value Pr(>|t|)    
z.lag.1      0.005386   0.002655   2.029  0.04592 *  
z.diff.lag1 -0.122887   0.098508  -1.247  0.21600    
z.diff.lag2 -0.048047   0.094165  -0.510  0.61134    
z.diff.lag3 -0.277911   0.096073  -2.893  0.00496 ** 
z.diff.lag4  0.549053   0.100822   5.446 5.95e-07 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 206800 on 77 degrees of freedom
Multiple R-squared:  0.5633,	Adjusted R-squared:  0.5349 
F-statistic: 19.86 on 5 and 77 DF,  p-value: 1.154e-12


Value of test-statistic is: 2.0289 

Critical values for test statistics: 
     1pct  5pct 10pct
tau

Los resultados ahora muestran consistencia con el comportamiento del PIB en la gráfica anterior. Esto es, con el estadístico ADF con constante no se puede  rechazar la hipótesis de raíz unitaria debido a que la tau estimada es  menor  en valor absoluto al valor crítico del 5% de la prueba: 0.69<-2.9. En el caso de  la prueba ADF sin constante y tendencia, el resultado muestra que la tau es positiva y con ello se indica que se encuentra en el caso de una raíz característica mayor que uno. En los dos casos, los resultados  concuerdan con el hecho de tener una serie con tendencia determinista y tal vez sea más adecuado aplicar el método de la regresión que con diferencias para eliminar la tendencia. En conclusión la serie del PIB no es estacionaria y por tanto el orden de integración es mayor a cero. 

Para determinar el orden de integración de las variables, se aplican las pruebas ADF con sus tre posibilidades:  1) tendencia y constante; 2) con constante; y, 3) sin constante ni tendencia, a la primera diferencia del logaritmo del PIB.   

In [13]:
# prueba con la derivada primera del log del PIB

lc.df <- ur.df(y=d_lpib_mex, type='trend', lags=4, selectlags=c("AIC"))

In [14]:
summary(lc.df)


############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression trend 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + tt + z.diff.lag)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.064879 -0.005980  0.001778  0.011136  0.045258 

Coefficients:
              Estimate Std. Error t value Pr(>|t|)    
(Intercept)  7.109e-03  5.161e-03   1.377   0.1726    
z.lag.1     -1.200e+00  2.753e-01  -4.359 4.15e-05 ***
tt           3.026e-06  9.451e-05   0.032   0.9745    
z.diff.lag1  2.265e-01  2.546e-01   0.890   0.3765    
z.diff.lag2  1.158e-01  2.011e-01   0.576   0.5665    
z.diff.lag3 -1.815e-01  1.587e-01  -1.144   0.2564    
z.diff.lag4  2.746e-01  1.130e-01   2.431   0.0175 *  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.01986 on 74 degrees of freedom
Multiple R-squared:  0.8218,	Adjusted R-squared:  0.8074 
F-statistic: 5

In [15]:
lc.df <- ur.df(y=d_lpib_mex, type='drift', lags=4, selectlags=c("AIC"))
summary(lc.df)


############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression drift 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + z.diff.lag)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.064994 -0.005982  0.001839  0.011256  0.045172 

Coefficients:
             Estimate Std. Error t value Pr(>|t|)    
(Intercept)  0.007248   0.002777   2.610   0.0109 *  
z.lag.1     -1.200561   0.273146  -4.395 3.59e-05 ***
z.diff.lag1  0.226823   0.252635   0.898   0.3721    
z.diff.lag2  0.116030   0.199591   0.581   0.5628    
z.diff.lag3 -0.181313   0.157503  -1.151   0.2533    
z.diff.lag4  0.274668   0.112201   2.448   0.0167 *  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.01973 on 75 degrees of freedom
Multiple R-squared:  0.8218,	Adjusted R-squared:  0.8099 
F-statistic: 69.19 on 5 and 75 DF,  p-value: < 2.2e-16


Value of test-statistic 

In [16]:
lc.df <- ur.df(y=d_lpib_mex, type='none', lags=4, selectlags=c("AIC"))
summary(lc.df)


############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression none 


Call:
lm(formula = z.diff ~ z.lag.1 - 1 + z.diff.lag)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.058897 -0.001654  0.006114  0.016373  0.050246 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)   
z.lag.1      -0.7631     0.2238  -3.411  0.00104 **
z.diff.lag1  -0.1450     0.2164  -0.670  0.50490   
z.diff.lag2  -0.1523     0.1775  -0.858  0.39351   
z.diff.lag3  -0.3580     0.1475  -2.427  0.01760 * 
z.diff.lag4   0.2061     0.1132   1.821  0.07257 . 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.02047 on 76 degrees of freedom
Multiple R-squared:  0.8057,	Adjusted R-squared:  0.7929 
F-statistic: 63.01 on 5 and 76 DF,  p-value: < 2.2e-16


Value of test-statistic is: -3.4106 

Critical values for test statistics: 
     1pct  5pct

Efectuando los tres tipos de pruebas para la variable en segundas diferencias se rechaza la hipótesis de raíz unitaria por lo que se puede concluir que la serie es integrada de orden uno  I(1): 4.35>-3.45, -4.39>-2.9 y -3.41>-1.95 respectivamente. 

##### Pruebas PP y  KPSS que complementa al la prueba ADF para análisis de integración del  PIB de la economía mexicana 

Para complementar los resultados obtenidos con la aplicación de la prueba ADF al logaritmo del PIB, se aplican las pruebas PP con tendencia y constante, y con constante junto a la prueba KPSS que no opciones sobre al tendencia y la constante.  
 
Los resultados de las pruebas PP que muestran a continuación para el caso de tendencia y constante, que el estadístico Z-tau (-4.19) > Z (-3.46) en términos absolutos, por lo que se concluye que se acepta la hipótesis alternativa de raíz no unitaria. Con la prueba PP solamente con constante, se encuentra que el estadístico Z-tau (-0.17269) < Z (-2.89) en términos absolutos, por lo que se concluye lo contrario y la variable tiene una raíz unitaria. Y, de acuerdo a la prueba KPSS el test-statistic  (0.1607) > que el valor critico (0.146), lo cual implica que se acepta la hipótesis alternativa de raíz unitaria.  Los  tres resultados son consistentes con lo encontrado con la prueba ADF y se concluye también que la variable L-pib_mex tiene raíz unitaria y por tanto no es estacionaría. 

In [17]:
# Prueba PP con constante y tendencia

lc.pp <- ur.pp(lpib_mex, type="Z-tau", model="trend", lags="long")
summary(lc.pp)


################################## 
# Phillips-Perron Unit Root Test # 
################################## 

Test regression with intercept and trend 


Call:
lm(formula = y ~ y.l1 + trend)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.074772 -0.011976  0.002096  0.019893  0.041381 

Coefficients:
             Estimate Std. Error t value Pr(>|t|)    
(Intercept) 5.3779514  1.3243709   4.061 0.000110 ***
y.l1        0.6678778  0.0818828   8.157 3.17e-12 ***
trend       0.0020822  0.0005293   3.934 0.000173 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.02464 on 83 degrees of freedom
Multiple R-squared:  0.9771,	Adjusted R-squared:  0.9765 
F-statistic:  1771 on 2 and 83 DF,  p-value: < 2.2e-16


Value of test-statistic, type: Z-tau  is: -4.1975 

           aux. Z statistics
Z-tau-mu              3.5396
Z-tau-beta            4.7490

Critical values for Z statistics: 
                     1pct      5pct     10pct
cr

In [18]:
# Prueba PP con constante

lc.pp <- ur.pp(lpib_mex, type="Z-tau", model="constant", lags="long")
summary(lc.pp)


################################## 
# Phillips-Perron Unit Root Test # 
################################## 

Test regression with intercept 


Call:
lm(formula = y ~ y.l1)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.079675 -0.015387  0.001721  0.018707  0.046483 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  0.27550    0.29008    0.95    0.345    
y.l1         0.98335    0.01793   54.84   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.02668 on 84 degrees of freedom
Multiple R-squared:  0.9728,	Adjusted R-squared:  0.9725 
F-statistic:  3008 on 1 and 84 DF,  p-value: < 2.2e-16


Value of test-statistic, type: Z-tau  is: -0.7269 

         aux. Z statistics
Z-tau-mu            0.7636

Critical values for Z statistics: 
                     1pct      5pct     10pct
critical values -3.507211 -2.895068 -2.584427


In [19]:
# Prueba KPSS para el logaritmo de la vrible PIB
lc.kpss <- ur.kpss(lpib_mex, type="tau", lags="short", use.lag = NULL)
summary(lc.kpss)


####################### 
# KPSS Unit Root Test # 
####################### 

Test is of type: tau with 3 lags. 

Value of test-statistic is: 0.1607 

Critical value for a significance level of: 
                10pct  5pct 2.5pct  1pct
critical values 0.119 0.146  0.176 0.216


Para complementar la identificación del orden de integración de la prueba ADF, a continuación se presentan los resultados de aplicar las pruebas PP y KPSS a la primera diferencia del logaritmo del PIB (d_lpib_mex). Con la prueba PP con tendencia y constante se encontró que el estadístico Ztau (-15.68) > Z-statistic (-3.46) en términos absolutos, con lo cual se rechaza la hipótesis de raíz unitaria; la misma conclusión se tiene con el resultado de la prueba PP con constante, el estadístico Z-tau (-15.70) > Z-statistic (-2.89) en términos absolutos; y, finalmente con la prueba KPSS se encuentra que el test-statistic  (0.038) < que el valor critico (0.146), lo cual confirma el resultado de las pruebas PP y ADF, de que la primera diferencia de la variable lpib_mex es estacionaria y por tanto su orden de integración es uno (I(1).  

In [20]:
# Prueba PP con tendencia y constante

lc.pp <- ur.pp(d_lpib_mex, type="Z-tau", model="trend", lags="long")
summary(lc.pp)


################################## 
# Phillips-Perron Unit Root Test # 
################################## 

Test regression with intercept and trend 


Call:
lm(formula = y ~ y.l1 + trend)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.086707 -0.010604  0.000978  0.013443  0.050041 

Coefficients:
              Estimate Std. Error t value Pr(>|t|)    
(Intercept)  8.727e-03  2.777e-03   3.142 0.002332 ** 
y.l1        -3.940e-01  1.015e-01  -3.882 0.000208 ***
trend       -3.409e-05  1.102e-04  -0.309 0.757946    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.02493 on 82 degrees of freedom
Multiple R-squared:  0.1557,	Adjusted R-squared:  0.1351 
F-statistic: 7.563 on 2 and 82 DF,  p-value: 0.0009675


Value of test-statistic, type: Z-tau  is: -15.6839 

           aux. Z statistics
Z-tau-mu              4.6499
Z-tau-beta           -0.3625

Critical values for Z statistics: 
                     1pct      5pct     10p

In [21]:
lc.pp <- ur.pp(d_lpib_mex, type="Z-tau", model="constant", lags="long")
summary(lc.pp)


################################## 
# Phillips-Perron Unit Root Test # 
################################## 

Test regression with intercept 


Call:
lm(formula = y ~ y.l1)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.085464 -0.009809  0.000877  0.013973  0.051028 

Coefficients:
             Estimate Std. Error t value Pr(>|t|)    
(Intercept)  0.008706   0.002761   3.153 0.002250 ** 
y.l1        -0.393307   0.100896  -3.898 0.000196 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.0248 on 83 degrees of freedom
Multiple R-squared:  0.1547,	Adjusted R-squared:  0.1446 
F-statistic:  15.2 on 1 and 83 DF,  p-value: 0.0001957


Value of test-statistic, type: Z-tau  is: -15.7046 

         aux. Z statistics
Z-tau-mu            3.5841

Critical values for Z statistics: 
                     1pct      5pct     10pct
critical values -3.508125 -2.895469 -2.584638


In [23]:
# Pruebas KPSS para la primera diferencia del logaritmo de la variable PIB
lc.kpss <- ur.kpss(d_lpib_mex, type="tau", lags="short", use.lag = NULL)
summary(lc.kpss)


####################### 
# KPSS Unit Root Test # 
####################### 

Test is of type: tau with 3 lags. 

Value of test-statistic is: 0.0387 

Critical value for a significance level of: 
                10pct  5pct 2.5pct  1pct
critical values 0.119 0.146  0.176 0.216
